apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralserver
  labels:
    app: centralserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralserver
  template:
    metadata:
      labels:
        app: centralserver
    spec:
      containers:
        - name: newserver
          image: abdelaziz89/servereses:v1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: parquet
              mountPath: /files
              subPath: files
      volumes:
        - name: parquet
          persistentVolumeClaim:
            claimName: serverstorage
