apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralserver
  labels:
    app: centralserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centralserver
  template:
    metadata:
      labels:
        app: centralserver
    spec:
      containers:
        - name: newserver
          image: abdelaziz89/central-server:v16.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/mnt/Volume"
              name: parquet
            - mountPath: "/mnt/Storage"
              name: parquet
      volumes:
        - name: parquet
          persistentVolumeClaim:
            claimName: serverstorage
