apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/c/Users/abdel/Desktop/Connect-4/Weather-Stations-Monitoring/BaseCentralStation/Volume"