apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serverstorage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeName: storage
