apiVersion: apps/v1
kind: Deployment
metadata:
  name: station4
  labels:
    app: station4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station4
  template:
    metadata:
      labels:
        app: station4
    spec:
      containers:
        - name: station4
          image: abdelaziz89/weather-station:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: StationId
              value: "4"
            - name: latitude
              value: "30.5148"
            - name: longitude
              value: "30.3436"
