apiVersion: apps/v1
kind: Deployment
metadata:
  name: station1
  labels:
    app: station1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station1
  template:
    metadata:
      labels:
        app: station1
    spec:
      containers:
        - name: station1
          image: abdelaziz89/weather:v1.0
          ports:
            - containerPort: 8080
